Convert to Swift 3
dbettermann/DBAlertController pull request #14
Opened 2016-09-08 07:05 UTC by ANNotunzdY

2016-09-09 20:43 UTC, joeboyscout04 commented
+1 would be great to add this since Xcode 8 is released.

2016-09-11 18:53 UTC, dbettermann commented
I'm thinking the Swift 3 upgrade should be on a separate branch and Swift 2.3 should be merged into master. That's the way I've seen a lot of other repos do it.

@ANNotunzdY you ok with changing the base branch?

2016-09-11 21:18 UTC, ANNotunzdY commented
@dbettermann OK, I'll change the base. Please create a branch for swift 3.

2016-09-11 21:23 UTC, dbettermann commented
It is created.

2016-09-29 13:06 UTC, ataranlen approved these changes
Tested on XCode 8, compiling against the current swift language version.

2016-10-01 21:25 UTC, dbettermann commented on Source/DBAlertController.swift
> +    fileprivate override var prefersStatusBarHidden : Bool {
Can you remove the space before the colon? I try to follow the Ray Wenderlich style guide. (https://github.com/raywenderlich/swift-style-guide#spacing)

2016-10-01 21:25 UTC, dbettermann commented on Source/DBAlertController.swift
> +    fileprivate override var preferredStatusBarStyle : UIStatusBarStyle {
Can you remove the space before the colon? I try to follow the Ray Wenderlich style guide. (https://github.com/raywenderlich/swift-style-guide#spacing)

2016-10-01 21:26 UTC, dbettermann requested changes
Make the two small changes I commented about and this branch can be merged in.

2016-10-02 00:26 UTC, dbettermann commented
I updated the master branch to support Swift 2.3, so it looks like you'll have to fix a few small conflicts.

2016-10-03 05:30 UTC, ANNotunzdY commented on Source/DBAlertController.swift
> +    fileprivate override var preferredStatusBarStyle : UIStatusBarStyle {
Sorry, I fixed it.

2016-10-06 22:51 UTC, dbettermann approved these changes

2016-10-06 22:51 UTC, dbettermann commented
Once you resolve your merge conflicts I can merge it in.

2016-10-11 06:24 UTC, ANNotunzdY commented
I merged the conflicts.

2016-10-11 20:19 UTC, dbettermann commented
Thanks!

2016-10-11 20:20 UTC, merged